size: [100, 40, 10]
source_region: [0, 5, 30, 30]
moved_region: [40, 5, 45, 30]
moved_spacing: 4
material: glass
surface_height: 0
coeff_friction: 0.4
youngs_modulus: 70000000000
poisson_ratio: 0.22
density: 2500
surface_energy: 0.1
